#!/usr/bin/env bash
#prints bad luck for the 4th loop iteration,
# good luck for the 8th loop iteration,
#Best School for the other iterations

i=0
while ((i < 10))
do
	((i++))
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi		
done
